'use strict';

function generateHookScript(name, content) {
  return `#!/bin/bash
# ${name}
# Auto-generated by claude-setup

${content}
`;
}

function generate(answers, detected) {
  const { hooks, notifyPlatform, formatCommand, lintCommand } = answers;
  const result = { scripts: {}, settingsHooks: {} };

  if (!hooks || hooks.length === 0) return result;

  // ── Notification hook ────────────────────────────────────────────────────────
  if (hooks.includes('notify')) {
    const notifyCmd = notifyPlatform === 'linux'
      ? `notify-send "Claude Code" "$MESSAGE"`
      : notifyPlatform === 'bell'
      ? `printf '\\a'`
      : `osascript -e "display notification \\"$MESSAGE\\" with title \\"Claude Code\\""`;

    result.scripts['notify.sh'] = generateHookScript('notify.sh',
`INPUT=$(cat)
MESSAGE=$(echo "$INPUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('message','Claude needs attention'))" 2>/dev/null || echo "Claude needs attention")
${notifyCmd}
exit 0`);

    result.settingsHooks.Notification = result.settingsHooks.Notification || [];
    result.settingsHooks.Notification.push({
      matcher: '',
      hooks: [{
        type: 'command',
        command: '.claude/hooks/notify.sh',
      }],
    });
  }

  // ── Protect against destructive commands ─────────────────────────────────────
  if (hooks.includes('protect')) {
    result.scripts['protect.sh'] = generateHookScript('protect.sh',
`INPUT=$(cat)
COMMAND=$(echo "$INPUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('command',''))" 2>/dev/null || echo "")

if echo "$COMMAND" | grep -qE 'rm\\s+-rf|rm\\s+--recursive.*-f|rm\\s+-[a-z]*r[a-z]*f'; then
  echo "Blocked: rm -rf is not allowed. Use rm with explicit paths or move to trash instead." >&2
  exit 2
fi

if echo "$COMMAND" | grep -qE 'DROP\\s+TABLE|DROP\\s+DATABASE|TRUNCATE\\s+TABLE'; then
  echo "Blocked: destructive SQL operation requires manual confirmation." >&2
  exit 2
fi

exit 0`);

    result.settingsHooks.PreToolUse = result.settingsHooks.PreToolUse || [];
    result.settingsHooks.PreToolUse.push({
      matcher: 'Bash',
      hooks: [{
        type: 'command',
        command: '.claude/hooks/protect.sh',
        timeout: 5,
      }],
    });
  }

  // ── Format on save ────────────────────────────────────────────────────────────
  if (hooks.includes('format') && formatCommand) {
    const cmd = formatCommand.trim();

    // Determine if the formatter accepts a single file or runs on all files
    const fileBasedFormatters = ['prettier', 'black', 'ruff', 'biome'];
    const isFileBased = fileBasedFormatters.some(f => cmd.includes(f));

    let scriptBody;
    if (isFileBased) {
      scriptBody =
`INPUT=$(cat)
FILE=$(echo "$INPUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('file_path',''))" 2>/dev/null || echo "")

if [ -n "$FILE" ] && [ -f "$FILE" ]; then
  ${cmd.replace(/ \.$/, '')} "$FILE" 2>/dev/null || true
fi
exit 0`;
    } else {
      scriptBody =
`${cmd} 2>/dev/null || true
exit 0`;
    }

    result.scripts['format.sh'] = generateHookScript('format.sh', scriptBody);

    result.settingsHooks.PostToolUse = result.settingsHooks.PostToolUse || [];
    result.settingsHooks.PostToolUse.push({
      matcher: 'Edit|Write',
      hooks: [{
        type: 'command',
        command: '.claude/hooks/format.sh',
        timeout: 30,
      }],
    });
  }

  // ── Lint on save ─────────────────────────────────────────────────────────────
  if (hooks.includes('lint') && lintCommand) {
    const cmd = lintCommand.trim();
    result.scripts['lint.sh'] = generateHookScript('lint.sh',
`INPUT=$(cat)
FILE=$(echo "$INPUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('file_path',''))" 2>/dev/null || echo "")

if [ -n "$FILE" ] && [ -f "$FILE" ]; then
  OUTPUT=$(${cmd.replace(/ \.$/, '')} "$FILE" 2>&1)
  EXIT_CODE=$?
  if [ $EXIT_CODE -ne 0 ]; then
    echo "Lint issues found:" >&2
    echo "$OUTPUT" >&2
    # Return exit 0 so Claude sees the output as info, not a block
  fi
fi
exit 0`);

    result.settingsHooks.PostToolUse = result.settingsHooks.PostToolUse || [];
    result.settingsHooks.PostToolUse.push({
      matcher: 'Edit|Write',
      hooks: [{
        type: 'command',
        command: '.claude/hooks/lint.sh',
        timeout: 60,
      }],
    });
  }

  // ── Run tests after edit ─────────────────────────────────────────────────────
  if (hooks.includes('tests') && detected.commands?.test) {
    const testCmd = detected.commands.test;
    result.scripts['test-on-save.sh'] = generateHookScript('test-on-save.sh',
`INPUT=$(cat)
FILE=$(echo "$INPUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('file_path',''))" 2>/dev/null || echo "")

# Only run tests if a source file was edited (not test files themselves)
if [[ "$FILE" != *".test."* ]] && [[ "$FILE" != *".spec."* ]] && [[ "$FILE" != */tests/* ]]; then
  ${testCmd} 2>&1 | tail -20
fi
exit 0`);

    result.settingsHooks.PostToolUse = result.settingsHooks.PostToolUse || [];
    result.settingsHooks.PostToolUse.push({
      matcher: 'Edit|Write',
      hooks: [{
        type: 'command',
        command: '.claude/hooks/test-on-save.sh',
        timeout: 120,
      }],
    });
  }

  // ── Audit log ────────────────────────────────────────────────────────────────
  if (hooks.includes('log')) {
    result.scripts['log.sh'] = generateHookScript('log.sh',
`INPUT=$(cat)
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
echo "$TIMESTAMP $INPUT" >> .claude/tool-log.jsonl
exit 0`);

    result.settingsHooks.PostToolUse = result.settingsHooks.PostToolUse || [];
    result.settingsHooks.PostToolUse.push({
      matcher: '',
      hooks: [{
        type: 'command',
        command: '.claude/hooks/log.sh',
        timeout: 5,
      }],
    });
  }

  return result;
}

module.exports = { generate };
