'use strict';

// Note: In SKILL.md files, shell command blocks use !`cmd` syntax.
// In JS template literals, backticks must be escaped as \`.
// So !`cmd` in a template literal is written as !\`cmd\`

const SKILL_TEMPLATES = {
  'pr-summary': () => [
    '---',
    'name: pr-summary',
    'description: Summarizes pull request changes with context and impact assessment. Use when creating or reviewing a PR.',
    'argument-hint: [pr-number]',
    'user-invocable: true',
    'allowed-tools: Bash, Read, Glob, Grep',
    '---',
    '',
    '## PR Context',
    '```',
    '!`git log --oneline main..HEAD 2>/dev/null | head -20 || git log --oneline -10`',
    '```',
    '',
    '## Changed Files',
    '```',
    '!`git diff --name-status main..HEAD 2>/dev/null || git diff --name-status HEAD~5..HEAD`',
    '```',
    '',
    '## Diff Summary',
    '```',
    '!`git diff --stat main..HEAD 2>/dev/null || git diff --stat HEAD~5..HEAD`',
    '```',
    '',
    'Write a concise pull request summary including:',
    '',
    '1. **What changed** — high-level description of the changes',
    '2. **Why** — the motivation or problem being solved',
    '3. **Impact** — what is affected (API changes, behavior changes, dependencies)',
    '4. **Testing** — what was tested and how to verify',
    '5. **Review notes** — anything reviewers should pay special attention to',
    '',
    'Keep it clear and focused. Use markdown formatting.',
    'If $ARGUMENTS contains a PR number, reference it.',
  ].join('\n'),

  'explain': () => [
    '---',
    'name: explain',
    'description: Explains code with diagrams, analogies, and step-by-step walkthroughs. Use when you need to understand how code works.',
    'argument-hint: <filepath or function name>',
    'user-invocable: true',
    'allowed-tools: Read, Grep, Glob',
    '---',
    '',
    'Explain the code at: $ARGUMENTS',
    '',
    'Your explanation must include:',
    '',
    '1. **What it does** — 1-2 sentence summary',
    '2. **Real-world analogy** — relate the concept to something non-technical',
    '3. **How it works** — step-by-step walkthrough of the logic',
    '4. **Key concepts** — any patterns, algorithms, or techniques used',
    '5. **ASCII diagram** — if the code involves data flow, state, or relationships, draw it',
    '6. **Common gotchas** — things that are easy to misunderstand',
    '',
    'Adjust your explanation to be clear to a developer unfamiliar with this specific code.',
    'If no specific path is provided in $ARGUMENTS, ask which code to explain.',
  ].join('\n'),

  'test-gen': () => [
    '---',
    'name: test-gen',
    'description: Generates comprehensive tests for a file or function. Use when you need test coverage for existing code.',
    'argument-hint: <filepath>',
    'user-invocable: true',
    'allowed-tools: Read, Grep, Glob, Write, Edit, Bash',
    '---',
    '',
    'Generate tests for: $ARGUMENTS',
    '',
    'Steps:',
    '1. Read the target file to understand all exports',
    '2. Read existing tests (if any) to match the style and patterns',
    '3. For each exported function/class, write tests covering:',
    '   - Happy path (normal expected input)',
    '   - Error cases (invalid input, thrown errors)',
    '   - Edge cases (empty, null, boundary values)',
    '4. Follow the test naming convention: `it(\'should <behavior> when <condition>\')`',
    '5. Run the tests to confirm they pass',
    '',
    'If the test file already exists, add to it rather than replacing it.',
    'If $ARGUMENTS is blank, ask which file to generate tests for.',
  ].join('\n'),

  'todo': () => [
    '---',
    'name: todo',
    'description: Creates a structured implementation plan from a feature request or issue description.',
    'argument-hint: <feature description>',
    'user-invocable: true',
    'allowed-tools: Read, Grep, Glob',
    '---',
    '',
    'Feature request: $ARGUMENTS',
    '',
    'Analyze the codebase and create a structured implementation plan:',
    '',
    '## 1. Understanding',
    '- What exactly needs to be built?',
    '- Who is affected (users, APIs, DB)?',
    '',
    '## 2. Files to Change',
    'List specific files that need to be created or modified.',
    '',
    '## 3. Implementation Steps',
    'Break down into small, discrete tasks. Each task should be:',
    '- Completable in one sitting',
    '- Independently testable',
    '- Clearly defined',
    '',
    '## 4. Testing Plan',
    'How will we verify this works correctly?',
    '',
    '## 5. Risks & Considerations',
    '- Breaking changes?',
    '- Performance implications?',
    '- Security considerations?',
    '- Dependencies needed?',
    '',
    'Be specific — reference actual file paths and function names from the codebase.',
  ].join('\n'),

  'review': () => [
    '---',
    'name: review',
    'description: Performs a thorough code review with a structured checklist and actionable feedback.',
    'argument-hint: [filepath or PR branch]',
    'user-invocable: true',
    'allowed-tools: Read, Grep, Glob, Bash',
    '---',
    '',
    'Review: $ARGUMENTS',
    '',
    'Perform a comprehensive code review. Read all changed files carefully.',
    '',
    '## Review Checklist',
    '',
    '### Functionality',
    '- [ ] Code does what it claims',
    '- [ ] Edge cases handled (null, empty, errors)',
    '- [ ] No obvious bugs',
    '',
    '### Code Quality',
    '- [ ] Functions are focused and well-named',
    '- [ ] No unnecessary duplication',
    '- [ ] Readable without needing comments to understand',
    '',
    '### Security',
    '- [ ] No hardcoded secrets',
    '- [ ] Input validated',
    '- [ ] No SQL injection / XSS risks',
    '',
    '### Testing',
    '- [ ] New code has tests',
    '- [ ] Tests cover edge cases',
    '',
    '### Performance',
    '- [ ] No obvious N+1 or inefficiencies',
    '',
    '---',
    '',
    'Provide feedback organized by:',
    '**Critical** → **Major** → **Minor** → **Suggestions**',
    '',
    'For each issue: reference the file/line and explain the problem and solution.',
    'If $ARGUMENTS is blank, review the most recently modified files.',
  ].join('\n'),

  'optimize': () => [
    '---',
    'name: optimize',
    'description: Analyzes code for performance issues and suggests optimizations. Use when code is slow or inefficient.',
    'argument-hint: <filepath>',
    'user-invocable: true',
    'allowed-tools: Read, Grep, Glob, Bash',
    '---',
    '',
    'Analyze performance of: $ARGUMENTS',
    '',
    '## Performance Analysis',
    '',
    '1. **Profile first** — identify the actual bottleneck before optimizing',
    '   - Are there N+1 database queries?',
    '   - Unnecessary recomputations or re-renders?',
    '   - Blocking I/O that could be async?',
    '   - Inefficient loops or data structures?',
    '',
    '2. **Measure the impact**',
    '   - How often is this code called?',
    '   - Is this actually a bottleneck?',
    '',
    '3. **Optimize with evidence**',
    '   - For each suggested optimization: explain the expected improvement',
    '   - Prefer readable optimizations over micro-optimizations',
    '   - Profile after to verify the improvement',
    '',
    'Provide concrete suggestions with before/after code examples.',
    'Prioritize by impact: high-impact changes first.',
  ].join('\n'),

  'changelog': () => [
    '---',
    'name: changelog',
    'description: Generates a CHANGELOG entry from recent git history. Use before a release.',
    'argument-hint: [version]',
    'user-invocable: true',
    'allowed-tools: Bash',
    '---',
    '',
    '## Recent Commits',
    '```',
    '!`git log --oneline --no-merges $(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)..HEAD 2>/dev/null | head -50`',
    '```',
    '',
    'Generate a CHANGELOG entry for version: $ARGUMENTS',
    '',
    'Format as standard Keep a Changelog (https://keepachangelog.com):',
    '',
    '## [$ARGUMENTS] - YYYY-MM-DD',
    '',
    '### Added',
    '- ...',
    '',
    '### Changed',
    '- ...',
    '',
    '### Fixed',
    '- ...',
    '',
    '### Removed',
    '- ...',
    '',
    'Group commits by type. Write in past tense from the user\'s perspective.',
    'Omit chore/internal commits that don\'t affect users.',
    'Keep entries concise — one line per change.',
  ].join('\n'),

  'scaffold': () => [
    '---',
    'name: scaffold',
    'description: Scaffolds a new component, module, or feature following project conventions. Use when creating something new.',
    'argument-hint: <name> [type]',
    'user-invocable: true',
    'allowed-tools: Read, Grep, Glob, Write, Edit',
    '---',
    '',
    'Scaffold: $ARGUMENTS',
    '',
    'Steps:',
    '1. Read 2-3 existing examples of similar components/modules in the codebase',
    '2. Identify the patterns, file naming conventions, and structure used',
    '3. Create the new scaffold following exactly those conventions',
    '4. Include:',
    '   - Main implementation file with proper structure',
    '   - Test file following existing test patterns',
    '   - Any required type definitions or interfaces',
    '   - Exports in appropriate index files',
    '',
    'Match the existing code style precisely — indentation, naming, import order.',
    'If the type/category is ambiguous, ask for clarification before creating files.',
  ].join('\n'),
};

function generate(selectedSkills) {
  const result = {};
  for (const name of selectedSkills) {
    const template = SKILL_TEMPLATES[name];
    if (template) {
      result[name] = template();
    }
  }
  return result;
}

module.exports = { generate };
